### ISSUE TITLE
How safe is bankscrap

### ISSUE THREAD

**Issue by kiteloopdesign** [bankscrap/bankscrap#61]
Hey guys, awesome project, thank so much for the work and sharing it !

Let me though address you with I think a reasonable question: how safe is to share the bank password with you? :) 

Maybe you can point me to the code where the password is handled? But how do I know that it is not used anywhere else?

Don't get me wrong, I appreciate what you guys have done, but I think many people might have this same question, especially for the ones not versed with Ruby.

Gracias!

**Comment by javiercr** [comment]
Credentials (user, password, etc.) never leave your computer and are never stored (that's why you need to either pass them to the CLI or to the Ruby API on each invocation). 

But don't just take my word for granted, take a look to the code :). Each bank adapter implements its own `login` method in `bank.rb`, here is the BBVA one:
https://github.com/bankscrap/bankscrap-bbva/blob/master/lib/bankscrap/bbva/bank.rb#L129

Another way for being sure that credentials are not sent anywhere else would be to use a proxy (Charles Proxy or mitmproxy) to log any HTTP request made by Ruby, and you'll see that bankscrap only send requests to your bank API endpoint and nowhere else.

Happy to answer any other questions!

**Comment by kiteloopdesign** [comment]
Muchas gracias Javi!

Muy buena esa del proxy, le echare un vistazo, me van a venir bien para algun que otro proyecto!

Estoy intentando automatizar mis cuentas con ledger y este proyecto es parte fundamental del flow! :)
